sonar.projectKey=ramakrishnanyadav_CampusOS
sonar.organization=ramakrishnanyadav
sonar.sources=src,server.ts
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.ts
sonar.exclusions=scratch/**,node_modules/**,dist/**,public/**,.gemini/**
