export const CONFIG_WORKFLOW = {
  SLA_DUE_MINUTES: 15,
  AUTOMATIC_ESCALATION_ENABLED: true,
  STATE_TRANSITIONS: {
    DRAFT: ['PENDING'],
    PENDING: ['APPROVED', 'REJECTED'],
    APPROVED: ['EXECUTING'],
    EXECUTING: ['COMPLETED', 'FAILED'],
    COMPLETED: ['ARCHIVED'],
    REJECTED: ['ARCHIVED'],
    FAILED: ['PENDING'],
  },
};
