export enum Capability {
  // Incident Management
  INCIDENT_VIEW = 'INCIDENT_VIEW',
  INCIDENT_MANAGE = 'INCIDENT_MANAGE',
  INCIDENT_RESOLVE = 'INCIDENT_RESOLVE',

  // Document OCR Pipeline
  OCR_VIEW = 'OCR_VIEW',
  OCR_UPLOAD = 'OCR_UPLOAD',
  OCR_EDIT = 'OCR_EDIT',
  OCR_APPROVE = 'OCR_APPROVE',
  OCR_WRITE = 'OCR_WRITE',

  // Timetable Scheduling
  TIMETABLE_READ = 'TIMETABLE_READ',
  TIMETABLE_SOLVE = 'TIMETABLE_SOLVE',
  TIMETABLE_APPROVE = 'TIMETABLE_APPROVE',
  TIMETABLE_EXPORT = 'TIMETABLE_EXPORT',
  TIMETABLE_WRITE = 'TIMETABLE_WRITE',

  // Spatial Attendance
  ATTENDANCE_READ = 'ATTENDANCE_READ',
  ATTENDANCE_WRITE = 'ATTENDANCE_WRITE',
  ATTENDANCE_APPROVE = 'ATTENDANCE_APPROVE',
  ATTENDANCE_EXPORT = 'ATTENDANCE_EXPORT',

  // Staffing & HR Intelligence
  STAFFING_VIEW = 'STAFFING_VIEW',
  STAFFING_PREDICT = 'STAFFING_PREDICT',
  STAFFING_WRITE = 'STAFFING_WRITE',
  STAFFING_APPROVE = 'STAFFING_APPROVE',
  STAFFING_PUBLISH = 'STAFFING_PUBLISH',

  // Infrastructure Management
  INFRASTRUCTURE_READ = 'INFRASTRUCTURE_READ',
  INFRASTRUCTURE_WRITE = 'INFRASTRUCTURE_WRITE',
  CAMPUS_MAP_VIEW = 'CAMPUS_MAP_VIEW',
  CONFIG_WRITE = 'CONFIG_WRITE',
}

export type CapabilityType = keyof typeof Capability;
